
# A config file for your Supabase project
project_id = "satshobhbkjptsbmfsia"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPv6"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://satshobhbkjptsbmfsia.supabase.co"]
jwt_expiry = 3600
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.admin-user-management]
verify_jwt = true

[functions.dropdown-options]
verify_jwt = true

[functions.generate-prep-notes]
verify_jwt = true

[functions.generate-question-coaching]
verify_jwt = true

[functions.generate-stage-summary]
verify_jwt = true

[functions.send-email]
verify_jwt = true
