-- Add preparation notes columns to interview_questions for server-side OpenAI-generated notes
-- Notes are generated once per question and reused by all users; idempotency via prompt hash

ALTER TABLE public.interview_questions
  ADD COLUMN IF NOT EXISTS preparation_notes jsonb DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS preparation_notes_generated_at timestamptz DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS preparation_notes_prompt_hash text DEFAULT NULL;

COMMENT ON COLUMN public.interview_questions.preparation_notes IS 'Array of 3-4 concise preparation note strings, generated by OpenAI once per question';
COMMENT ON COLUMN public.interview_questions.preparation_notes_generated_at IS 'When preparation_notes were last generated';
COMMENT ON COLUMN public.interview_questions.preparation_notes_prompt_hash IS 'Hash of inputs (question, role, category, stage, details) used for idempotent caching';
